apiVersion: v1
kind: Pod
metadata:
  name: check-backup-pod
spec:
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: overlord-backup
  containers:
    - name: check-backup-container
      image: registry.devops.rivtower.com/library/busybox:1.30
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - mountPath: "/backup"
          name: backup